---
# LimitRange template for tenant namespaces
# Ensures pods have resource requests/limits set

apiVersion: v1
kind: LimitRange
metadata:
  name: tenant-limits
  namespace: nextcloud-platform
  labels:
    app.kubernetes.io/name: policies
    app.kubernetes.io/component: governance
    template: "true"
  annotations:
    description: "Template limit range for tenant namespaces"
spec:
  limits:
    # Default limits for containers
    - type: Container
      default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
      min:
        cpu: "10m"
        memory: "32Mi"
      max:
        cpu: "4"
        memory: "8Gi"
    
    # Limits for pods
    - type: Pod
      max:
        cpu: "8"
        memory: "16Gi"
    
    # PVC size limits
    - type: PersistentVolumeClaim
      min:
        storage: "1Gi"
      max:
        storage: "100Gi"

