---
# ApplicationSet that generates Nextcloud Applications for each tenant
# Tenants are defined by files in nextcloud-platform/values/tenants/
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nextcloud-tenants
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  # Enable Go templating so we can safely default missing keys.
  # This keeps existing tenants working when tenant.namespace is not set.
  goTemplate: true
  # We reference .tenant.namespace with a default; it may be missing for older tenants.
  goTemplateOptions: ["missingkey=default"]
  # Prevent accidental deletion of tenant applications
  syncPolicy:
    preserveResourcesOnDeletion: true
  
  # Generator: create one Application per tenant file
  # Alle tenant-*.yaml bestanden worden automatisch opgepikt
  # UITGEZONDERD: templates/tenant-template.yaml (staat in andere folder)
  generators:
    - git:
        repoURL: "https://github.com/ConductionNL/Nextcloud-base.git"
        revision: HEAD
        files:
          - path: "nextcloud-platform/values/tenants/tenant-*.yaml"
  
  # Application template
  template:
    metadata:
      name: "nc-{{ .tenant.name }}"
      namespace: argocd
      labels:
        app.kubernetes.io/part-of: nextcloud-platform
        nextcloud.platform/tenant: "{{ .tenant.name }}"
        nextcloud.platform/environment: "{{ .tenant.environment }}"
      annotations:
        argocd.argoproj.io/sync-wave: "{{ .tenant.wave }}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: nextcloud-platform
      
      # Source: Nextcloud Helm chart with our values
      sources:
        # Main Nextcloud Helm chart
        - repoURL: "https://nextcloud.github.io/helm/"
          chart: nextcloud
          targetRevision: "8.9.0"
          helm:
            releaseName: "nextcloud"
            valueFiles:
              - "$values/nextcloud-platform/values/common.yaml"
              - "$values/nextcloud-platform/values/env/{{ .tenant.environment }}.yaml"
              - "$values/nextcloud-platform/values/tenants/tenant-{{ .tenant.name }}.yaml"
            values: |
              fullnameOverride: "nextcloud"
              commonLabels:
                nextcloud.platform/tenant: "{{ .tenant.name }}"
                nextcloud.platform/environment: "{{ .tenant.environment }}"
        
        # Our GitOps repo for values files
        - repoURL: "https://github.com/ConductionNL/Nextcloud-base.git"
          targetRevision: HEAD
          ref: values
      
      # Destination: tenant-specific namespace
      destination:
        server: https://kubernetes.default.svc
        # Namespace is tenant-configurable (must be unique per tenant).
        # Example: tenant.namespace: "test-mariadb"
        namespace: "{{ default (printf \"nc-%s\" .tenant.name) .tenant.namespace }}"
      
      # Sync policy
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
          - ServerSideApply=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
      
      revisionHistoryLimit: 10
      
      ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas
