---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: redis
  namespace: nextcloud-platform
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
      app.kubernetes.io/component: cache

