---
# PgBouncer uses the same postgres-admin secret as database provisioning
# This Job just verifies the secret exists
apiVersion: batch/v1
kind: Job
metadata:
  name: pgbouncer-secret-check
  namespace: nextcloud-platform
  labels:
    app.kubernetes.io/name: pgbouncer
    app.kubernetes.io/component: secret-check
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pgbouncer
        app.kubernetes.io/component: secret-check
    spec:
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: secret-generator
      containers:
        - name: check
          image: bitnami/kubectl:1.28
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          command:
            - /bin/bash
            - -c
            - |
              set -e
              
              SECRET_NAME="postgres-admin"
              NAMESPACE="nextcloud-platform"
              
              echo "Checking for PostgreSQL admin secret..."
              
              if kubectl get secret "$SECRET_NAME" -n "$NAMESPACE" &>/dev/null; then
                echo "✓ Secret $SECRET_NAME exists"
                
                # Verify required keys
                for key in host port username password; do
                  if kubectl get secret "$SECRET_NAME" -n "$NAMESPACE" -o jsonpath="{.data.$key}" &>/dev/null; then
                    echo "  ✓ Key '$key' present"
                  else
                    echo "  ✗ Key '$key' missing!"
                    exit 1
                  fi
                done
                
                echo ""
                echo "All required keys present."
                exit 0
              else
                echo ""
                echo "=========================================="
                echo "ERROR: PostgreSQL admin secret not found!"
                echo "=========================================="
                echo ""
                echo "Create it with:"
                echo ""
                echo "  export POSTGRES_HOST='your-postgresql-host'"
                echo "  export POSTGRES_PORT='5432'"
                echo "  export POSTGRES_ADMIN_USER='postgres'"
                echo "  export POSTGRES_ADMIN_PASSWORD='your-admin-password'"
                echo "  ./scripts/create-postgres-admin-secret.sh"
                echo ""
                exit 1
              fi
