---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pgbouncer
  namespace: nextcloud-platform
  labels:
    app.kubernetes.io/name: pgbouncer
    app.kubernetes.io/component: database-proxy
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pgbouncer
      app.kubernetes.io/component: database-proxy

