---
# Default values for tenant-resources
# These are overridden by ApplicationSet

tenant:
  name: ""
  environment: "accept"
  namespace: ""
  dbType: "mariadb"

# Secret store reference
secretStore:
  name: cluster-secret-store
  kind: ClusterSecretStore

# Secret refresh interval
refreshInterval: 1h

