---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nextcloud-platform

resources:
  - cluster.yaml

commonLabels:
  app.kubernetes.io/name: nextcloud-pg
  app.kubernetes.io/component: database
  app.kubernetes.io/part-of: nextcloud-platform
  app.kubernetes.io/managed-by: argocd
