---
# ClusterSecretStore configuration
#
# CURRENT STATUS: Using Kubernetes Secrets directly (fallback mode)
#
# For production, consider migrating to External Secrets Operator with:
# - HashiCorp Vault
# - AWS Secrets Manager  
# - Azure Key Vault
# - GCP Secret Manager
#
# See: https://external-secrets.io/latest/provider/

# Kubernetes Secrets fallback store
# Uses secrets created manually or by the create-tenant-secret.sh script
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: kubernetes-secret-store
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: secrets-management
    app.kubernetes.io/part-of: nextcloud-platform
spec:
  provider:
    kubernetes:
      # Reference secrets in a dedicated namespace
      remoteNamespace: nextcloud-secrets
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: kube-system
          key: ca.crt
      auth:
        serviceAccount:
          name: external-secrets-reader
          namespace: nextcloud-platform

---
# NOTE: The following stores are templates for future use
# Uncomment and configure when ready to migrate to a secrets backend

# Option 1: HashiCorp Vault (recommended for on-prem)
# apiVersion: external-secrets.io/v1beta1
# kind: ClusterSecretStore
# metadata:
#   name: vault-secret-store
# spec:
#   provider:
#     vault:
#       server: "https://vault.example.com:8200"
#       path: "secret"
#       version: "v2"
#       auth:
#         kubernetes:
#           mountPath: "kubernetes"
#           role: "nextcloud-platform"
#           serviceAccountRef:
#             name: external-secrets
#             namespace: nextcloud-platform

# Option 2: AWS Secrets Manager
# apiVersion: external-secrets.io/v1beta1
# kind: ClusterSecretStore
# metadata:
#   name: aws-secret-store
# spec:
#   provider:
#     aws:
#       service: SecretsManager
#       region: eu-west-1
#       auth:
#         jwt:
#           serviceAccountRef:
#             name: external-secrets
#             namespace: nextcloud-platform
