---
# yamllint configuration for Nextcloud Platform

extends: relaxed

rules:
  # Allow longer lines for Helm templates and configs
  line-length:
    max: 200
    level: warning
  
  # Truthy values in YAML
  truthy:
    check-keys: false
    allowed-values:
      - "true"
      - "false"
      - "yes"
      - "no"
      - "on"
      - "off"
  
  # Comments
  comments:
    min-spaces-from-content: 1
  
  # Document start marker not required
  document-start: disable
  
  # Indentation
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false
  
  # Brackets
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
  
  # Braces
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  
  # Colons
  colons:
    max-spaces-before: 0
    max-spaces-after: -1
  
  # Commas
  commas:
    max-spaces-before: 0
    min-spaces-after: 1
    max-spaces-after: 1
  
  # Hyphens
  hyphens:
    max-spaces-after: 1
  
  # Empty lines
  empty-lines:
    max: 2
    max-start: 0
    max-end: 1

ignore:
  # Ignore generated files
  - "*.generated.yaml"
  - "rendered/"

