---
# Job to copy postgres-admin secret from platform namespace to tenant namespace
# This is needed because the db-provision job runs in the tenant namespace
apiVersion: batch/v1
kind: Job
metadata:
  name: copy-postgres-admin-{{ .Values.tenant.name }}
  namespace: {{ .Values.tenant.namespace | default (printf "nc-%s" .Values.tenant.name) }}
  labels:
    {{- include "tenant-resources.labels" . | nindent 4 }}
    app.kubernetes.io/component: secret-copy
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "-5"
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 3
  template:
    metadata:
      labels:
        {{- include "tenant-resources.labels" . | nindent 8 }}
        app.kubernetes.io/component: secret-copy
    spec:
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: secret-generator
      containers:
        - name: copy
          image: bitnami/kubectl:1.28
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          command:
            - /bin/bash
            - -c
            - |
              set -e
              
              SOURCE_NS="nextcloud-platform"
              TARGET_NS="{{ .Values.tenant.namespace | default (printf "nc-%s" .Values.tenant.name) }}"
              SECRET_NAME="postgres-admin"
              
              echo "Copying $SECRET_NAME from $SOURCE_NS to $TARGET_NS..."
              
              # Check if source secret exists
              if ! kubectl get secret "$SECRET_NAME" -n "$SOURCE_NS" &>/dev/null; then
                echo "ERROR: Secret $SECRET_NAME not found in $SOURCE_NS"
                echo ""
                echo "Create it with:"
                echo "  ./scripts/create-postgres-admin-secret.sh"
                exit 1
              fi
              
              # Copy secret to tenant namespace
              kubectl get secret "$SECRET_NAME" -n "$SOURCE_NS" -o yaml | \
                sed "s/namespace: $SOURCE_NS/namespace: $TARGET_NS/" | \
                kubectl apply -f -
              
              echo "✓ Secret copied to $TARGET_NS"

