---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.tenant.namespace | default (printf "nc-%s" .Values.tenant.name) }}
  labels:
    {{- include "tenant-resources.labels" . | nindent 4 }}
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted

